//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "advancedPageSettings"
	/// <summary>Advanced Page Settings</summary>
	public partial interface IAdvancedPageSettings : IPublishedElement
	{
		/// <summary>Instructions</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ApsInstructions { get; }

		/// <summary>Background Colour</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string BackgroundColour { get; }

		/// <summary>Background image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		IPublishedContent BackgroundImage { get; }

		/// <summary>Background image options</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		Newtonsoft.Json.Linq.JToken BackgroundImageOptions { get; }

		/// <summary>Button color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string ButtonColor { get; }

		/// <summary>Component width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		Options Width { get; }
	}

	/// <summary>Advanced Page Settings</summary>
	[PublishedModel("advancedPageSettings")]
	public partial class AdvancedPageSettings : PublishedElementModel, IAdvancedPageSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "advancedPageSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AdvancedPageSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AdvancedPageSettings(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Instructions: {div class="panel-body"}{p}These settings only apply if this component has been added to the "Homepage" or an "Advanced Page / Advanced Page Blog Post".{/p}{/div}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("apsInstructions")]
		public string ApsInstructions => GetApsInstructions(this);

		/// <summary>Static getter for Instructions</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetApsInstructions(IAdvancedPageSettings that) => that.Value<string>("apsInstructions");

		///<summary>
		/// Background Colour: Color selected will dictate the color to be used for any text.  If a background image is used, select the color that works best for the text over the image.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("backgroundColour")]
		public string BackgroundColour => GetBackgroundColour(this);

		/// <summary>Static getter for Background Colour</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetBackgroundColour(IAdvancedPageSettings that) => that.Value<string>("backgroundColour");

		///<summary>
		/// Background image: No recommended image size. To cover the full area of the component use a large image. Use a small image to repeat.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("backgroundImage")]
		public IPublishedContent BackgroundImage => GetBackgroundImage(this);

		/// <summary>Static getter for Background image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedContent GetBackgroundImage(IAdvancedPageSettings that) => that.Value<IPublishedContent>("backgroundImage");

		///<summary>
		/// Background image options
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("backgroundImageOptions")]
		public Newtonsoft.Json.Linq.JToken BackgroundImageOptions => GetBackgroundImageOptions(this);

		/// <summary>Static getter for Background image options</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static Newtonsoft.Json.Linq.JToken GetBackgroundImageOptions(IAdvancedPageSettings that) => that.Value<Newtonsoft.Json.Linq.JToken>("backgroundImageOptions");

		///<summary>
		/// Button color: Selects the colour of the button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("buttonColor")]
		public string ButtonColor => GetButtonColor(this);

		/// <summary>Static getter for Button color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetButtonColor(IAdvancedPageSettings that) => that.Value<string>("buttonColor");

		///<summary>
		/// Component width
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("width")]
		public Options Width => GetWidth(this);

		/// <summary>Static getter for Component width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static Options GetWidth(IAdvancedPageSettings that) => that.Value<Options>("width");
	}
}
