//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "pageNavigationSettings"
	/// <summary>Page Navigation Settings</summary>
	public partial interface IPageNavigationSettings : IPublishedContent
	{
		/// <summary>Breadcrumb link text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string BreadcrumbLinkText { get; }

		/// <summary>Hide breadcrumb</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		object HideBreadcrumb { get; }

		/// <summary>Hide from all navigation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		object UmbracoNaviHide { get; }
	}

	/// <summary>Page Navigation Settings</summary>
	[PublishedModel("pageNavigationSettings")]
	public partial class PageNavigationSettings : PublishedContentModel, IPageNavigationSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "pageNavigationSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageNavigationSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PageNavigationSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Breadcrumb link text: Node name will be used by default if nothing is entered.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("breadcrumbLinkText")]
		public string BreadcrumbLinkText => GetBreadcrumbLinkText(this);

		/// <summary>Static getter for Breadcrumb link text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetBreadcrumbLinkText(IPageNavigationSettings that) => that.Value<string>("breadcrumbLinkText");

		///<summary>
		/// Hide breadcrumb
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("hideBreadcrumb")]
		public object HideBreadcrumb => GetHideBreadcrumb(this);

		/// <summary>Static getter for Hide breadcrumb</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static object GetHideBreadcrumb(IPageNavigationSettings that) => that.Value("hideBreadcrumb");

		///<summary>
		/// Hide from all navigation: Prevents this page from being shown in most menus
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("umbracoNaviHide")]
		public object UmbracoNaviHide => GetUmbracoNaviHide(this);

		/// <summary>Static getter for Hide from all navigation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static object GetUmbracoNaviHide(IPageNavigationSettings that) => that.Value("umbracoNaviHide");
	}
}
