//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "scripts"
	/// <summary>Scripts</summary>
	public partial interface IScripts : IPublishedContent
	{
		/// <summary>After opening body scripts</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string PageAfterOpeningBodyScripts { get; }

		/// <summary>Before closing body scripts</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string PageBeforeClosingBodyScripts { get; }

		/// <summary>Header scripts</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		string PageHeaderScripts { get; }
	}

	/// <summary>Scripts</summary>
	[PublishedModel("scripts")]
	public partial class Scripts : PublishedContentModel, IScripts
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "scripts";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Scripts, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Scripts(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// After opening body scripts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageAfterOpeningBodyScripts")]
		public string PageAfterOpeningBodyScripts => GetPageAfterOpeningBodyScripts(this);

		/// <summary>Static getter for After opening body scripts</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetPageAfterOpeningBodyScripts(IScripts that) => that.Value<string>("pageAfterOpeningBodyScripts");

		///<summary>
		/// Before closing body scripts: Anything you enter here will be placed before the closing &lt;/body&gt; tag on this page of your website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageBeforeClosingBodyScripts")]
		public string PageBeforeClosingBodyScripts => GetPageBeforeClosingBodyScripts(this);

		/// <summary>Static getter for Before closing body scripts</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetPageBeforeClosingBodyScripts(IScripts that) => that.Value<string>("pageBeforeClosingBodyScripts");

		///<summary>
		/// Header scripts: Anything you enter here will be placed before the closing &lt;/head&gt; tag on this page of your website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pageHeaderScripts")]
		public string PageHeaderScripts => GetPageHeaderScripts(this);

		/// <summary>Static getter for Header scripts</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static string GetPageHeaderScripts(IScripts that) => that.Value<string>("pageHeaderScripts");
	}
}
